### PR TITLE
Lib updates

### PR DESCRIPTION
**Pull request by ButuzGOL**

### CODE REVIEW

**Comment by john-benson** [comment]
I was actually going to post an issue about this. There are currently features that gave been fully deprecated in React15 that this project relies on.

This PR will cause warnings to be thrown and also break the CheckboxGroup component.

I recommend holding off on this PR

**Comment by ButuzGOL** [comment]
Agreed wait for warnings fixes

**Comment by stomita** [comment]
@ButuzGOL Is it enough to set the key to each elements for just prevent warning in React 15 ? If you have to change the current CheckboxGroup to support it (especially state handling) ?

**Comment by ButuzGOL** [comment]
> Is it enough to set the key to each elements for just preventing warning in React 15 ?
When we are given React array it wants keys so there several solutions
1. Just add keys
2. Write function which wrapping list items and add keys
3. add keys inside renderFormElement
so I choose 1 but if you see another point we can change

>  Do you have to change the current CheckboxGroup to support it (especially state handling)  ?
Yeah react given warning when you have value and defaultChecked (but I still cant understand why create https://github.com/facebook/react/issues/6779) so I rebuild to state using checked and value (as for me its much clear with state)
But lets wait for response

**Comment by stomita** [comment]
@ButuzGOL 

> so I choose 1 but if you see another point we can change

I mean the setting key explicitly is OK but it seems it includes different type of fix in one PR.

> Yeah react given warning when you click on radio with exists item with defaultChecked (but I still cant understand why create facebook/react#6779) so I rebuild to state using checked and value (as for me its much clear with state)

I'm not sure the behavior here should be handled in each lib which uses uncontrolled checkbox/radios. If the change is intended in React 15 I can't find any reason of it (it seems there is no way for checkbox/radio to stay "uncontrolled"). We should ignore this until the purpose becomes clear.

**Comment by ButuzGOL** [comment]
> I mean the setting key explicitly is OK but it seems it includes different type of fix in one PR.
Its not clear what you suggest ?

> We should ignore this until the purpose becomes clear.
Was apply to issue so seems like its bug I will revert changes

**Comment by stomita** [comment]
@ButuzGOL 

> Its not clear what you suggest ?

The part you included to work around the React 15's change about checkbox/radio controlled/uncontrolled behavior is to be separated as we can accept the rest of PR.

**Comment by ButuzGOL** [comment]
I did revert 
Problem with keys not relates to React 15 so can be fixed next
and checkbox/radio this is React 15 bug (it works fine but gives warning)

**Comment by ButuzGOL** [comment]
any feedback ?

**Comment by ButuzGOL** [comment]
are you going to merge this pull because I am going in next pr update eslinter

**Comment by ButuzGOL** [comment]
@stomita is there way to get fast feedback ? Because if so slow feedback its hard to contribute

**Comment by stomita** [comment]
@ButuzGOL Sorry I was longly caught by a different project and could not review them. Merged.

**Pull request merged**
