### PR TITLE
Test structure

### PR DESCRIPTION
**Pull request by ButuzGOL**
- Karma
- Mocha
- Sinon, Chai
- Istanbul
- react-addons-test-utils

### CODE REVIEW

**Comment by ButuzGOL** [comment]
Please accept this pull or lets discuss

**Comment by ButuzGOL** [comment]
Why so long response I want to merge this pull and #15 so to move further ?
Currently I have two free days to do open source but I don't want to start because my pulls still no feedback
I think firstly we should have good env for dev
1. webpack will make dev much better #15 
2. test coverage its very important in open source
And then easily develop components

**Comment by stomita** [comment]
I don't think the response is taking so long. We should investigate the structure before merging it. The origin of this lib comes from our local and private development works so sometime it conflicts our local preference of developing way. We have a right to carefully choosing the suitable tech stacks as the author.

**Comment by ButuzGOL** [comment]
Thanks for quick feedback
The only thing is to have feedback before weekends would be nice

**Comment by ButuzGOL** [comment]
Also I wanted to add that my english no perfect so I can write no carefully or not by rules so its can sounds bad
Thanks for explanation

**Pull request merged**
