### PR TITLE
Added support for validation to Input & Textarea

### PR DESCRIPTION
**Pull request by jkentjnr**
You can enable validation for Input & Textarea using the following syntax:

```javascript
<Input label='Name' placeholder='Name' value={ this.state.name } onChange={ this.onInputChange.bind(this, 'name') } required={true} validate={ this.state.validate } />
```

This enables me to:
- mark the element as mandatory using the required param
- force validation when I want by setting the validate param to true

The onChange event has an additional param passed to the event handler.  This param is used to indicate whether the input is valid.  This could be extended to be pluggable.

### CODE REVIEW

**Comment by stomita** [comment]
Could you add some examples in `examples/client/scripts/components/FormExamples.js` ?

**Comment by jkentjnr** [comment]
Yeah cool. I'll look into it shortly.

**Comment by zokito** [comment]
@jkentjnr will consider adding the examples so we can use the  validation on forms?

**Comment by jkentjnr** [comment]
@zokito Hope to shortly - have had deadlines on projects.

**Comment by jkentjnr** [comment]
This is failing with a lint error:
"Value must be omitted for boolean attributes"

Not sure what how to address setting a boolean prop any differently... Any advice?

**Comment by stomita** [comment]
In airbnb eslint config, the notation like

```
<Input required={ true } />
```

should be like:

```
<Input required />
```

**Comment by jkentjnr** [comment]
Any feedback?  If not, can we merge this?

**Comment by stomita** [comment]
@jkentjnr Added comments to the commit lines.

**Comment by david-a** [comment]
Hi! +1 for merging this one ASAP :) thanks!

**Comment by stomita** [comment]
IMO current PR is not good when it comes to extending validation logic, it is embedded inside of the component class and not customizable for component users.

My suggestion for the improvement is just allow passing `errorMessage` to the component, and listen `onChange` event to update the message. No validation logic should be inside of the component class.

**Comment by david-a** [comment]
I agree, but a solution of some sort is needed here, since there is no access to the classes of the FormElement (in order to add `slds-is-required` or `slds-has-error`). 

My solution was to just let `required`, and `valid` props to get through the various components (Input, DateInput, Lookup, etc.) into FormElement and assign the relevant classnames there. But it can be done in other ways (e.g. exposing the FormElement class attr so it can be assigned from the outside)

**Comment by stomita** [comment]
I will close this PR and create new to support minimal for showing required mark and error message.

**Comment by david-a** [comment]
@stomita I've created a minimal changes PR for this issue: https://github.com/stomita/react-lightning-design-system/pull/45

**Pull request closed without merging**
