### PR TITLE
Example folder moved from express to webpack closes #9

### LINKED ISSUE #9: Env for dev too slow
I did some development and its very slow 
because after every change babel compile all lib and it takes much time
So I think we should try webpack with hot reloading or gulp browserify with partial load

### PR DESCRIPTION
**Pull request by ButuzGOL**
Hot reloading enabled

### CODE REVIEW

**Comment by ButuzGOL** [comment]
Any feedback on this ?

**Comment by stomita** [comment]
Hot loading with webpack is nice idea for those who actively contributes code to this lib, however, as they are served in an example project, we need to keep the structure simple, not directly depending to the source modules. I declared the dependency in local module path in package.json so that it can be used by replacing it to published npm package in real project.

**Comment by ButuzGOL** [comment]
In this way we can create two folders 
one is docs where we can do for those "who actively contribute code to this lib"
and second is examples where we can do for those "that it can be used by replacing it to published npm package in real project"

what do you think as its done in https://github.com/callemall/material-ui
I tried to develop using current state and webpack and webpack much better

**Comment by stomita** [comment]
> In this way we can create two folders 

I also thought this kind of thing. Could you suggest the preferable structure to support it in PR ?

**Comment by ButuzGOL** [comment]
Ok will add it to this pull

**Comment by ButuzGOL** [comment]
Please review this commit
Give comments or do over commit
I think further we can add descriptions to components inside doc so everybody can see components props/methods

**Comment by stomita** [comment]
The codes in `doc` directory I don't want to maintain them as separated from examples. If it is separated we need to check additionally the `doc` directory src to be surely working in development.

Is it possible to keep `examples` directory as same and create a webpack build project for dev users which references the code in examples ?

**Comment by ButuzGOL** [comment]
Yes you right one folder is much better please take a look on new pull #22

**Comment by stomita** [comment]
@ButuzGOL #22 seems neat and merged it. Thanks.

**Pull request closed without merging**
